# ***First we import the python library from scientific computation library we import the stats ***

In [43]:
import numpy as np
import pandas as pd
from scipy import stats

# **Given the data is below**

In [44]:
df =[1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32, 0.85, 1.07, 1.48, 1.20, 1.33, 1.18, 1.22, 1.29]
df

[1.13,
 1.55,
 1.43,
 0.92,
 1.25,
 1.36,
 1.32,
 0.85,
 1.07,
 1.48,
 1.2,
 1.33,
 1.18,
 1.22,
 1.29]

In [45]:
n=len(df)

In [46]:
n

15

# **Task a. Build 99% Confidence Interval Using Sample Standard Deviation**

# **and we calculated the sample mean**

In [47]:
sample_mean=np.mean(df)
sample_mean

1.2386666666666666

# **And also calculated the sample standard devition**

In [48]:
sample_std_dev=np.std(df)
sample_std_dev

0.18661427836285438

# **And we find the degrees of freedom it means the total number of the data it minus 1**

In [49]:
d_f=n-1
d_f

14

# **here we calculate the critical value from t-distribution for 99% confidence leve**

In [50]:
t_critical=stats.t.ppf(0.99,df)
t_critical

array([21.94662127, 10.50880338, 12.3427023 , 42.38558208, 16.79511416,
       13.76211214, 14.73193776, 57.19127574, 25.73013743, 11.50096869,
       18.63962698, 14.47696936, 19.48701023, 17.85814436, 15.5526357 ])

# **here i calculate margin of error**

In [51]:
margin_of_error=t_critical*(sample_std_dev/np.sqrt(n))
margin_of_error

array([1.05746721, 0.50635197, 0.59471582, 2.04228991, 0.80924905,
       0.6631081 , 0.70983779, 2.75568152, 1.23977064, 0.55415807,
       0.89812432, 0.69755249, 0.9389543 , 0.86046968, 0.74938197])

In [52]:
sample_mean-margin_of_error

array([ 1.81199458e-01,  7.32314694e-01,  6.43950843e-01, -8.03623244e-01,
        4.29417613e-01,  5.75558567e-01,  5.28828878e-01, -1.51701486e+00,
       -1.10396972e-03,  6.84508597e-01,  3.40542346e-01,  5.41114173e-01,
        2.99712370e-01,  3.78196991e-01,  4.89284697e-01])

In [53]:
sample_mean+margin_of_error

array([2.29613388, 1.74501864, 1.83338249, 3.28095658, 2.04791572,
       1.90177477, 1.94850446, 3.99434819, 2.4784373 , 1.79282474,
       2.13679099, 1.93621916, 2.17762096, 2.09913634, 1.98804864])

# **Confidence interval Calculation**

In [54]:
confidence_interval=(sample_mean-margin_of_error,sample_mean+margin_of_error)
confidence_interval

(array([ 1.81199458e-01,  7.32314694e-01,  6.43950843e-01, -8.03623244e-01,
         4.29417613e-01,  5.75558567e-01,  5.28828878e-01, -1.51701486e+00,
        -1.10396972e-03,  6.84508597e-01,  3.40542346e-01,  5.41114173e-01,
         2.99712370e-01,  3.78196991e-01,  4.89284697e-01]),
 array([2.29613388, 1.74501864, 1.83338249, 3.28095658, 2.04791572,
        1.90177477, 1.94850446, 3.99434819, 2.4784373 , 1.79282474,
        2.13679099, 1.93621916, 2.17762096, 2.09913634, 1.98804864]))

In [55]:
print('Task a:--Build 99% Confidence Interval Using Sample Standard Deviation')
print('\n')
print('Sample Mean:--',sample_mean)
print('\n')
print('Sample standard devition :--',sample_std_dev)
print('\n')
print('Confidence Interval:--',confidence_interval)
print('\n')

Task a:--Build 99% Confidence Interval Using Sample Standard Deviation


Sample Mean:-- 1.2386666666666666


Sample standard devition :-- 0.18661427836285438


Confidence Interval:-- (array([ 1.81199458e-01,  7.32314694e-01,  6.43950843e-01, -8.03623244e-01,
        4.29417613e-01,  5.75558567e-01,  5.28828878e-01, -1.51701486e+00,
       -1.10396972e-03,  6.84508597e-01,  3.40542346e-01,  5.41114173e-01,
        2.99712370e-01,  3.78196991e-01,  4.89284697e-01]), array([2.29613388, 1.74501864, 1.83338249, 3.28095658, 2.04791572,
       1.90177477, 1.94850446, 3.99434819, 2.4784373 , 1.79282474,
       2.13679099, 1.93621916, 2.17762096, 2.09913634, 1.98804864]))




# **Task b. Build 99% Confidence Interval Using Known Population Standard Deviation**

# **Given population standard deviation**

In [56]:
population_std_dev=0.2
population_std_dev

0.2

# **Critical value from z-distribution for 99% confidence level**

In [57]:
z_critical=stats.norm.ppf(0.99)
z_critical

2.3263478740408408

In [58]:
margin_error=z_critical*(population_std_dev/np.sqrt(n))
margin_error

0.12013208764860274

In [59]:
sample_mean-margin_error

1.1185345790180639

In [60]:
sample_mean+margin_error

1.3587987543152693

# **Confidence Interval Calculation**

In [61]:
confidence_i=(sample_mean-margin_error,sample_mean+margin_error)
confidence_i

(1.1185345790180639, 1.3587987543152693)

In [62]:
print('Task b. Build 99% Confidence Interval Using Known Population Standard Deviation')
print('\n')
print('Sample Mean:--',sample_mean)
print('\n')
print('Population Standard Devition:--',population_std_dev)
print('\n')
print('Confidence Interval:--',confidence_i)

Task b. Build 99% Confidence Interval Using Known Population Standard Deviation


Sample Mean:-- 1.2386666666666666


Population Standard Devition:-- 0.2


Confidence Interval:-- (1.1185345790180639, 1.3587987543152693)
