# ***Import the libraries ***

In [ ]:
import numpy as np
import pandas as pd
from scipy import stats
from scipy.stats import chi2_contingency

# **Here Data provided**

In [ ]:
observed_values=np.array([[50,70],
                          [80,100],
                          [60,90],
                          [30,50],
                          [20,50]])
observed_values

array([[ 50,  70],
       [ 80, 100],
       [ 60,  90],
       [ 30,  50],
       [ 20,  50]])

# **Here CalCulate Row and Column Totals**

In [ ]:
row_totals=observed_values.sum(axis=1)
column_totals=observed_values.sum(axis=0)
grand_totals=observed_values.sum()

# **Here we calculated the expected values**

In [ ]:
expected_values=np.outer(row_totals,column_totals)/grand_totals

In [ ]:
expected_values

array([[ 48.,  72.],
       [ 72., 108.],
       [ 60.,  90.],
       [ 32.,  48.],
       [ 28.,  42.]])

# **State Hypotheses:**

1. Null Hypotheses :- there is a no association between the type of smart device and customer satisfication level

2. Alternative Hypotheses:-There is an association between the type of smart device and customer satisfication

# **Compute the Chi-Square Statistics:**

In [ ]:
chi_square=((observed_values-expected_values)**2/expected_values)
chi_square

array([[0.08333333, 0.05555556],
       [0.88888889, 0.59259259],
       [0.        , 0.        ],
       [0.125     , 0.08333333],
       [2.28571429, 1.52380952]])

In [ ]:
chi_square.sum()

5.638227513227513

# **Here Determine the degrees of freedom**

In [ ]:
df=(observed_values[0]-1)*(observed_values.shape[1]-1)
df

array([49, 69])

# **Here given the alpha value**
# **alpha=0.05**

In [ ]:
alpha=0.05
critical_value=stats.chi2.ppf(1-alpha,df)
critical_value

array([66.33864886, 89.39120787])

# **Here calculate the p-value**

In [ ]:
p_value=1-stats.chi2.cdf(chi_square,df)
p_value

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# **Make Decision**

In [ ]:
if (chi_square > critical_value).any():
    print("Reject the null hypothesis. There is a significant association between device type and customer satisfaction.")
else:
    print("Fail to reject the null hypothesis. No significant association between device type and customer satisfaction.")

Fail to reject the null hypothesis. No significant association between device type and customer satisfaction.
